import Lines from "@/components/Lines";
import "./globals.css";
import Dots from "@/components/Dots";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <div>
          <Lines />
          <Dots />
          {children}
        </div>
      </body>
    </html>
  );
}
